### ISSUE TITLE
Andorid Tv(Android Version 9) SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN

### ISSUE THREAD

**Issue by muqeeta96** [tronikos/androidtvremote2#12]
I am trying to connect with TCL Android TV which is running Android Version 9. This library fetches the name and MAC of the Android Tv device by using `async_get_name_and_mac()` but when I press **y** to start pairing. It start crashing and giving below stacktrace.

```
Traceback (most recent call last):
  File "/Users/abdulmuqeet/Desktop/androidtvremote2-0.0.14/src/androidtvremote2/androidtv_remote.py", line 202, in async_connect
    ) = await self._loop.create_connection(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1112, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 1145, in _create_connection_transport
    await waiter
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 575, in _on_handshake_complete
    raise handshake_exc
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/sslproto.py", line 557, in _do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/abdulmuqeet/Desktop/androidtvremote2-0.0.14/src/demo.py", line 202, in _main
    await remote.async_connect()
  File "/Users/abdulmuqeet/Desktop/androidtvremote2-0.0.14/src/androidtvremote2/androidtv_remote.py", line 221, in async_connect
    raise InvalidAuth("Need to pair") from exc
androidtvremote2.exceptions.InvalidAuth: Need to pair

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/abdulmuqeet/Desktop/androidtvremote2-0.0.14/src/demo.py", line 238, in <module>
    asyncio.run(_main(), debug=True)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/abdulmuqeet/Desktop/androidtvremote2-0.0.14/src/demo.py", line 206, in _main
    await _pair(remote)
  File "/Users/abdulmuqeet/Desktop/androidtvremote2-0.0.14/src/demo.py", line 148, in _pair
    await remote.async_start_pairing()
  File "/Users/abdulmuqeet/Desktop/androidtvremote2-0.0.14/src/androidtvremote2/androidtv_remote.py", line 358, in async_start_pairing
    await self._pairing_message_protocol.async_start_pairing()
  File "/Users/abdulmuqeet/Desktop/androidtvremote2-0.0.14/src/androidtvremote2/pairing.py", line 80, in async_start_pairing
    await self._async_wait_for_future_or_con_lost(self._on_pairing_started)
  File "/Users/abdulmuqeet/Desktop/androidtvremote2-0.0.14/src/androidtvremote2/pairing.py", line 140, in _async_wait_for_future_or_con_lost
    raise ConnectionClosed(future.exception())
androidtvremote2.exceptions.ConnectionClosed: Unhandled msg: 
``` 

**I already read the same issue which is closed https://github.com/tronikos/androidtvremote2/issues/5**

**Comment by tronikos** [comment]
Without access to your Android TV device it's hard for me to debug and fix this. So you are on your own fixing this. As a workaround you could try the zeroconf flow in Home Assistant as discussed in #5.

**Comment by muqeeta96** [comment]
Can you help me out? How is `async_get_name_and_mac() ` able to use `open_connection()` and get an SSL object while pairing and connecting using `create_connection()` and cause an SSL v3 error. Any guess

**Comment by muqeeta96** [comment]
My Android TV is not discovered with this `_androidtvremote2._tcp.local.` service type. While making a little change in service type to `_androidtvremote._tcp.local.` help discover my device. I still facing an issue of pairing and connection. Can you give any suggestions to reach solution

**Comment by tronikos** [comment]
Your device is using the old protocol. This library is meant for v2. Updating https://play.google.com/store/apps/details?id=com.google.android.tv.remote.service on your device should upgrade you to the new protocol.
